#!/usr/bin/env bash
# Configure Nginx listening port 80 of all the server’s active IPv4 IPs
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pgrep nginx -o > /run/nginx.pid
nginx -s reload
echo '' > /run/nginx.pid

