#!/usr/bin/env bash
# The same as task 0, -f added to ln for forceful remove the file if exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
