#!/usr/bin/env bash
# a Bash script displays the contents of the file `/etc/passwd`using while.
# should only displays the username, user id, and user home directory path.

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
